name: autodeploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install wasm workload
      run: dotnet workload install wasm-tools
    - name: Publish with dotnet
      run: dotnet publish CropperSampleV6 --configuration Release --output build
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.AUTODEPLOY_TOKEN }}
        branch: gh-page # The branch the action should deploy to.
        folder: build/wwwroot # The folder the action should deploy.
        single-commit: true
        repository-name: Chronostasys/chronostasys.github.io